name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        runner: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Update local toolchain
        run: |
          rustup update
      - name: Toolchain info
        run: |
          rustc --version
          cargo --version --verbose
      - name: Build debug
        run: |
          cargo build --all-features
      - name: Build release
        run: |
          cargo build --release --all-features
